"""add percent_risk required field to Trade model

Revision ID: 4738420e6c8c
Revises: e313dd1bfac2
Create Date: 2026-09-18 18:23:46.875340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4738420e6c8c'
down_revision: Union[str, Sequence[str], None] = 'e313dd1bfac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('percent_risk', sa.DECIMAL(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'percent_risk')
    # ### end Alembic commands ###
