"""add dollar_risk column and change quantity from INT to DECIMAL

Revision ID: b1f16d56d3aa
Revises: bb37ff2a2c43
Create Date: 2026-09-03 15:18:15.709450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f16d56d3aa'
down_revision: Union[str, Sequence[str], None] = 'bb37ff2a2c43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('dollar_risk', sa.DECIMAL(), nullable=False))
    op.alter_column('trades', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'quantity',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('trades', 'dollar_risk')
    # ### end Alembic commands ###
