"""fix exit_price to nullable True

Revision ID: bb37ff2a2c43
Revises: ca063cc3bc6a
Create Date: 2026-09-03 03:08:07.137749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb37ff2a2c43'
down_revision: Union[str, Sequence[str], None] = 'ca063cc3bc6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'exit_price',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'exit_price',
               existing_type=sa.NUMERIC(precision=14, scale=4),
               nullable=False)
    # ### end Alembic commands ###
