"""create TradingSystem and Trade models

Revision ID: ca063cc3bc6a
Revises: 5d3025fcca45
Create Date: 2026-08-29 13:30:46.658824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca063cc3bc6a'
down_revision: Union[str, Sequence[str], None] = '5d3025fcca45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_systems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('asset_class', sa.Enum('ALL', 'STOCKS', 'FOREX', 'CRYPTO', 'FUTURES', 'OPTIONS', 'ETFS', 'COMMODITIES', name='assetclass'), nullable=False),
    sa.Column('timeframe', sa.Enum('ONE_MINUTE', 'FIVE_MINUTE', 'FIFTEEN_MINUTE', 'THIRTY_MINUTE', 'ONE_HOUR', 'FOUR_HOUR', 'ONE_DAY', 'ONE_WEEK', 'ONE_MONTH', 'SIX_MONTH', name='tradetimeframe'), nullable=False),
    sa.Column('setup_requirements', sa.String(length=300), nullable=False),
    sa.Column('entry_rules', sa.String(length=100), nullable=False),
    sa.Column('stop_loss_rules', sa.String(length=100), nullable=True),
    sa.Column('take_profit_rules', sa.String(length=100), nullable=True),
    sa.Column('break_even_rules', sa.String(length=100), nullable=True),
    sa.Column('additional_rules', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_systems_user_id'), 'trading_systems', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trading_system_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('BULLISH', 'BEARISH', name='tradedirection'), nullable=False),
    sa.Column('entry_price', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('exit_price', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('stop_loss_price', sa.DECIMAL(precision=14, scale=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.String(length=30), nullable=True),
    sa.Column('closed_at', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'CANCELLED', name='tradestatus'), nullable=False),
    sa.Column('realized_pnl', sa.DECIMAL(precision=14, scale=4), nullable=True),
    sa.Column('realized_pnl_percent', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('result_r', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trading_system_id'], ['trading_systems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_trading_system_id'), 'trades', ['trading_system_id'], unique=False)
    op.create_index(op.f('ix_trades_user_id'), 'trades', ['user_id'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trades_user_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_trading_system_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_trading_systems_user_id'), table_name='trading_systems')
    op.drop_table('trading_systems')
    # ### end Alembic commands ###
